name: trendvibe_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # Iconos predeterminados
  cupertino_icons: ^1.0.8

  # Peticiones HTTP
  http: ^1.2.1

  # Almacenamiento seguro de tokens (KeyStore / Keychain)
  flutter_secure_storage: ^9.2.2

  # Base de datos local SQLite
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Detección de conexión (Modo Avión)
  connectivity_plus: ^6.0.3

  # Generador de UUID para la cola de peticiones
  uuid: ^4.4.0
  sqflite_common_ffi: ^2.4.0+3
  sqflite_common_ffi_web: ^1.1.1
  dio: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true